### ISSUE TITLE
Implementation of @ControllerAdvice for Exception Handling

### ISSUE THREAD

**Issue by LeNelSoN** [LeNelSoN/you-are-the-hero#24]
### Quest: 
We want to improve exception handling in our Spring application by using @ControllerAdvice. This will allow us to centralize exception management, enhance code cleanliness, and ensure a uniform response in case of errors.

### Current Problems:
- Exception handling is scattered across multiple controllers.
- Controller code is cluttered with try-catch blocks.
- Error responses are not uniform.

### Objectifs:

- [ ] Create the GlobalExceptionHandler class.
- [ ] Add methods to handle specific exceptions.
- [ ] Set up an error response structure.
- [ ] Write tests to verify correct functionality.

Feel free to add your thoughts or suggestions regarding this proposal.

![DALL·E-2024-10-02-17 16](https://github.com/user-attachments/assets/40371673-a346-4694-bb6f-fe8998661a58)

The keeper of the repo 🏰

**Comment by LeNelSoN** [comment]
Thank you @srinjoyghosh-bot, and I look forward to reviewing what you come up with.

**Comment by LeNelSoN** [comment]
Hello @srinjoyghosh-bot ,

I hope you're doing well! I wanted to check in regarding the issue you picked up for the project. We haven't seen any commits from you in the past week, and I just wanted to make sure everything is going smoothly.

If you've encountered any difficulties or need assistance, feel free to reach out, and we’ll be happy to help. If you're no longer able to work on the issue, please let us know so we can reassign it.

The keeper of the repo 🏰

**Comment by RamprasadRajasegar** [comment]
Hello @LeNelSoN ,

I am working on this. Since I am new to open-source contributions, give me two days, and I will push the code.
