### ISSUE TITLE
Assign "Player" Role During User Registration

### ISSUE THREAD

**Issue by LeNelSoN** [LeNelSoN/you-are-the-hero#25]
### Quest:
When a new user registers, they should automatically be assigned the "Player" role by default. 🎮 
This role is required to access the basic functionalities of the application.

### Objectifs:

- Update the user registration method in the appropriate service to assign the "Player" role to each new user.
- Ensure that the "Player" role is properly defined in the database. 💾
- Write and run tests to confirm the role is correctly assigned and permissions are properly configured. 🧪

![image](https://github.com/user-attachments/assets/13276d97-fe46-44e2-88ed-e1543905a497)

The keeper of the repo 🏰

**Comment by ArinNigam** [comment]
I would like to work on this issue

**Comment by LeNelSoN** [comment]
Thank you so much for your interest in working on this issue! Another contributor has already submitted a PR for it. Feel free to check out their PR and share any feedback or suggestions you may have. If you're looking for something else to work on, there are other open issues that might interest you!

You could also submit a PR to help document the work done on the registration process, if you'd like. I’d be happy to tag your PR for Hacktoberfest as well. 😊
