### ISSUE TITLE
Allow Admin to Assign "Editor" Role to Registered Users

### ISSUE THREAD

**Issue by LeNelSoN** [LeNelSoN/you-are-the-hero#26]
### Quest:
Implement functionality that allows administrators to assign the "Editor" role to existing registered users. This will enable certain users to create and edit content within the application. ✍️

### Objectives:

- Create the endpoint.
- Create a method in the appropriate service (UserService) to handle the assignment of the "Editor" role to a user. 🔑
- Ensure that only users with the "Admin" role can assign the "Editor" role. 🔒
- Validate the user's existence and the current roles before assigning the "Editor" role. ✅
- Write and run tests to confirm that the "Editor" role is correctly assigned and that permissions are properly enforced. 🧪

![image](https://github.com/user-attachments/assets/0e08bc72-3a8e-4733-b5c1-aa5029f0c226)

The keeper of the repo 🏰

**Comment by ArinNigam** [comment]
I would like to work on this issue

**Comment by LeNelSoN** [comment]
Hello @ArinNigam ,

I hope you're doing well! I wanted to check in regarding the issue you picked up for the project. We haven't seen any commits from you in the past week, and I just wanted to make sure everything is going smoothly.

If you've encountered any difficulties or need assistance, feel free to reach out, and we’ll be happy to help. If you're no longer able to work on the issue, please let us know so we can reassign it.

The keeper of the repo 🏰

**Comment by LeNelSoN** [comment]
Hi @ArinNigam ,

Just checking in to see if there’s any update. Let me know if you need any help!
