### ISSUE TITLE
Verify and strengthen user password security

### ISSUE THREAD

**Issue by LeNelSoN** [LeNelSoN/you-are-the-hero#3]
## Quest
Add additional constraints for passwords (e.g., minimum length, inclusion of special characters, etc.).

[Video Brute-Force Konbini](https://www.youtube.com/watch?v=YI-6nZFxwNg)

![image](https://github.com/user-attachments/assets/c52cdb02-ad30-4a7b-94dd-8079e9de2ac7)

The keeper of the repo 🏰

**Comment by GaneshLadaskar** [comment]
Hello Sir can you assign this issue to me? I am new in the field of open-source contribution but I will try to resolve your your issue
Thank You!

**Comment by LeNelSoN** [comment]
Hello @GaneshLadaskar ,

I’m so happy you’re ready to take on this quest! 🎉 I've assigned you to issue #3, and I’m excited to see what you’ll do. If you run into any challenges along the way, don’t hesitate to ask for help. I’m here to support you! 🛠️

When you’re done, feel free to submit a pull request, and I’ll review it as soon as possible.

Thanks again for joining this adventure! Let’s make it a success! 🚀

The keeper of the repo 🏰

**Comment by GaneshLadaskar** [comment]
I have sent you the pull request you can go through it and suggest any
changes Thank You!

**Comment by LeNelSoN** [comment]
Hi padawan @GaneshLadaskar ,

I noticed that you haven't created a Pull Request for your contribution yet. I took a look at your fork and saw that you made a commit to resolve the issue. To assist you, I've written some [documentation](https://github.com/LeNelSoN/you-are-the-hero/blob/main/How_to_create_a_pull_request.md) to guide you on how to create a Pull Request.

Additionally, I noticed that you added a piece of code in C++, whereas the project is in Java and uses Spring. I encourage you to refactor your code in Java so that we can integrate it into the project. Don't hesitate to familiarize yourself with the technologies used in the project; you'll find it fascinating!

Feel free to create the Pull Request so that you can receive feedback and advice.

Thank you for your contribution!

The keeper of the repo 🏰

**Comment by GaneshLadaskar** [comment]
OK I will take care of this next will making a pull request .

**Comment by LeNelSoN** [comment]
No worries, we're all here to learn, and everyone moves at their own pace. If you need help, feel free to ask or share your questions on this topic. 😊

**Comment by LeNelSoN** [comment]
Hello @GaneshLadaskar,

I hope you're doing well! I wanted to check in regarding the issue you picked up for the project. We haven't seen any commits from you in the past week, and I just wanted to make sure everything is going smoothly.

If you've encountered any difficulties or need assistance, feel free to reach out, and we’ll be happy to help. If you're no longer able to work on the issue, please let us know so we can reassign it.

The keeper of the repo 🏰
