### ISSUE TITLE
Use GitHub action to add hacktoberfest label to new issues 

### ISSUE THREAD

**Issue by JCarlosR** [LeNelSoN/you-are-the-hero#30]
@LeNelSoN The idea is to save you some time when new issues are added to the repo, while the event is active.
Please assign to me if you like it.

**Comment by LeNelSoN** [comment]
Of course, that’s a good idea!

**Comment by JCarlosR** [comment]
Please let me know if this works for you https://github.com/LeNelSoN/you-are-the-hero/pull/34
