### ISSUE TITLE
Documentation for Security Implementation

### ISSUE THREAD

**Issue by LeNelSoN** [LeNelSoN/you-are-the-hero#36]
### Quest: 
There is a need to enhance the documentation related to the security implementation in our project. Specifically, we need to provide clear guidelines on the use of access tokens and refresh tokens within the application.

### Objectives:

- Review the existing Spring Security documentation.
- Explain the purpose and functionality of access tokens and refresh tokens in our application.
- Provide examples of how to generate, validate, and refresh tokens in the context of our application.
- Include any additional information that may help contributors understand the security aspects of the project better.

### Additional Notes: 

Feel free to reach out if you have any questions or need further clarification on any aspect of the security implementation.

![image](https://github.com/user-attachments/assets/0302e0ee-ecd9-4f90-b6c1-ce3fb6615f18)

The keeper of the repo 🏰

**Comment by LeNelSoN** [comment]
https://docs.spring.io/spring-security/reference/index.html 😉

**Comment by fikirWalle** [comment]
Okay, I thought if we have already any existing security documentation in our project, but now I got it. :sunglasses:

**Comment by fikirWalle** [comment]
Hi there, could you close this issue? Please let me know if any changes are needed. I'd like to work on Endpoint for User Deletion #5 once it's closed
