### ISSUE TITLE
Write Unit Tests for StoryService

### ISSUE THREAD

**Issue by LeNelSoN** [LeNelSoN/you-are-the-hero#8]
## Quest:
Develop unit tests for the `StoryService` class to ensure that story creation and scene management functionalities work as expected.

## Tasks:

- Test `createNewStory` Method:

> - [ ] Verify that a new story can be created and saved successfully.
> - [ ] Ensure that the method throws an exception when trying to save a story with invalid data (if applicable).

- Test `addSceneToStory` Method:

> - [ ] Test successful addition of a scene to a story when the story exists and has no first scene.
> - [ ] Validate that it throws SceneAlreadyExistsException if a scene already exists for that story.
> - [ ] Ensure that it throws StoryNotFoundException if the story does not exist.
> - [ ] Check that it throws IllegalArgumentException if the story ID or scene is null.

- Test `getAllStory` Method:

> - [ ] Verify that all stories can be retrieved correctly from the repository.

- Test `getStoryById` Method:

> - [ ] Test retrieval of a story by its ID when it exists.
> - [ ] Validate that it throws StoryNotFoundException when the story does not exist.
> - [ ] Ensure that it throws IllegalArgumentException if the story ID is null or empty.

![image](https://github.com/user-attachments/assets/103a818f-7ed6-4c10-a399-0581d92827d7)

The keeper of the repo 🏰

**Comment by fikirWalle** [comment]
I would like to work on this Sir

**Comment by LeNelSoN** [comment]
Hi @fikirWalle ,

Thank you so much for contributing to improving the unit tests! 🙏 Feel free to add any additional test cases if you think they are necessary to cover more scenarios or enhance the robustness of the project. Any improvement in this regard is greatly appreciated.

If you have any questions or need clarification, don’t hesitate to reach out. I'm here to help.

Thanks again for your support!

The keeper of the repo 🏰

**Comment by fikirWalle** [comment]
Hi LeNelson,
Thank you for the opportunity. I apologize for the delayed response. Please find the changes I made today.

**Comment by LeNelSoN** [comment]
Thank you for your contribution! 🙌 I'll be reviewing your PR very soon. In the meantime, feel free to check out the changes made and the new issues that have been added. Don’t hesitate to reach out if you have any questions or feedback. 😊
