### ISSUE TITLE
Write Unit Tests for SceneService

### ISSUE THREAD

**Issue by LeNelSoN** [LeNelSoN/you-are-the-hero#9]
## Quest:
Develop unit tests for the `SceneService` class to ensure that scene management functionalities work correctly, including adding new scenes and retrieving scenes by ID.

## Tasks:

- Test `addNewScene` Method:

> - [ ] Verify that a new scene can be added successfully to an existing parent scene.
> - [ ] Ensure that a Scene is created and associated with the correct parent scene.
> - [ ] Validate that the method throws an exception when trying to add a scene to a non-existent parent scene.
> - [ ] Check that the choices are correctly added to the parent scene.

- Test getSceneById Method:

> - [ ] Test successful retrieval of a scene by its ID when it exists.
> - [ ] Validate that it throws a RuntimeException when the scene does not exist.

![image](https://github.com/user-attachments/assets/821d4429-8bba-4fc0-92f4-08005f5ee95f)

The keeper of the repo 🏰

**Comment by RomeoIndiaJulietUniform** [comment]
Hii @LeNelSoN  I add the unit tests for the Scene Service which covers the following :

1.The testAddNewScene_Success() method verifies that a new scene can be added to an existing parent scene, ensuring the correct creation of the child scene and updating of the parent scene's choices.

2.The testAddNewScene_ParentSceneNotFound() method checks that an exception is thrown when attempting to add a scene to a non-existent parent.

3.The testGetSceneById_Success() and testGetSceneById_SceneNotFound() methods test the retrieval of scenes by ID, confirming successful retrieval when the scene exists and proper exception handling when it doesn't.

Also added a .gitignore file. Please let me know if there are any additional tasks or improvements that need to be addressed. I'm open to any suggestions!
